### ISSUE TITLE
What about translating this workshop to English?

### ISSUE THREAD

**Issue by teobais** [JUGIstanbul/java9-workshop#3]
It will be interesting for other JUGs, too.

**Comment by apandichi** [comment]
@tanerdiler Thanks for the translation!
Side note: there is still an untranslated phrase in JAVA_9_WORKSHOP_EN.pdf, at WORKSHOP 4, section 2.a. (the one regarding PLC and OPC modules)

**Comment by tanerdiler** [comment]
@apandichi I've translated forgotten part. Please check pull request https://github.com/JUGIstanbul/java_9_10_workshop/pull/4.
